"""Add health and fitness goal fields to UserProfile

Revision ID: da603ec3e9cb
Revises: 2dcfdb5e3e4d
Create Date: 2025-09-07 14:33:11.507217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da603ec3e9cb'
down_revision: Union[str, Sequence[str], None] = '2dcfdb5e3e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('intolerances', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('health_conditions', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('fitness_goal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'fitness_goal')
    op.drop_column('user_profiles', 'health_conditions')
    op.drop_column('user_profiles', 'intolerances')
    op.drop_column('user_profiles', 'allergies')
    # ### end Alembic commands ###